program: main.py
method: grid
parameters:
  gnn_type:
    value: 'originalgin'
  num_layer:
    value: 4
  emb_dim:
    values: [16, 32]
  batch_size:
    values: [32, 128]
  learning_rate:
    values: [0.01, 0.001]
  decay_rate:
    value: 0.5
  decay_step:
    value: 50
  epochs:
    value: 350
  dataset:
    values: ['MUTAG', 'PTC', 'PROTEINS', 'NCI1', 'NCI109', 'IMDB-BINARY', 'IMDB-MULTI']
  drop_ratio:
    value: 0.
  channels:
    values: ['64-64']
  policy:
    values: ['null', 'node_marked', 'ego_nets', 'ego_nets_plus']
  model:
    value: 'sun'
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}