program: main.py
method: grid
parameters:
  gnn_type:
    values: ['originalgin']
  num_layer:
    values: [5, 6]
  emb_dim:
    values: [64, 96, 110]
  batch_size:
    values: [128]
  learning_rate:
    values: [0.001]
  decay_rate:
    value: 0.5
  decay_step:
    value: 50
  epochs:
    value: 250
  dataset:
    value: 'subgraphcount'
  drop_ratio:
    value: 0.
  channels:
    values: ['64-64']
  policy:
    values: ['ego_nets', 'ego_nets_plus']
  model:
    values: ['sun']
  task_idx:
    values: [0, 1, 2, 3]
  seed:
    values: [1,2,3]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}